<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="MAIN" Id="{43968a78-caf7-44cf-a620-5ef2552be001}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	nCounter: int;
	Var1 AT %I*: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Var1 := true;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="26" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>